- id: php-lint-all
  name: PHP Syntax Check (Comprehensive)
  description: Check PHP Syntax on ALL PHP staged files with user friendly messages and colors
  entry: pre_commit_hooks/php-lint.sh
  language: script
  files: \.php$
  args: [-s all]

- id: php-lint
  name: PHP Syntax Check (Quick)
  description: Runs php -l on all staged files. Exits when it hits the first errored file
  entry: php -l
  language: system
  files: \.php$

- id: php-unit
  name: PHP Unit
  description: Run the full php unit test. Checks which PHPUnit executable is available first and then runs it. Preference order is phpunit.phar, vendor/bin/phpunit, phpunit and bin/phpunit.
  entry: pre_commit_hooks/php-unit.sh
  language: script
  files: \.php$

- id: php-cs
  name: PHP Codesniffer
  description: Run php codesniffer against all staged files.
  entry: pre_commit_hooks/php-cs.sh
  language: script
  files: \.php$

- id: php-cbf
  name: PHP Codesniffer (Code Beutifier and Formatter)
  description: Run php codesniffer against all staged files.
  entry: pre_commit_hooks/php-cbf.sh
  language: script
  files: \.php$

- id: php-cs-fixer
  name: PHP Coding Standards Fixer
  description: Run php coding standards fixer against all staged files.
  entry: pre_commit_hooks/php-cs-fixer.sh
  language: script
  files: \.php$

- id: php-cs-fixer
  name: PHP Coding Standards Fixer
  description: Run php coding standards fixer against all staged files.
  entry: pre_commit_hooks/php-cs-fixer.sh
  language: script
  files: \.php$

- id: php-no-dumps
  name: PHP Ensure no dumps
  description: Checks for a call to symfony's dump
  entry: \s+dump\(|;dump\(|^dump\(
  language: pygrep
  files: \.php$

- id: php-no-var_dumps
  name: PHP Ensure no var_dumps
  description: Checks for var_dump calls
  entry: \s+var_dump\(|;var_dump\(|^var_dump\(
  language: pygrep
  files: \.php$

- id: php-no-exits
  name: PHP Ensure no exits or dies
  description: Checks for die and exit calls
  entry: \s+exit[;(]|;exit[;(]|^exit[;(]|\s+die[;(]|;die[;(]|^die[;(]
  language: pygrep
  files: \.php$
